config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do
    resources :answers, only: [:index, :show, :create] do
      collection do
        get :match
      end
    end
    
    resources :users, only: [:index, :show] do
      collection do
        get :profile
        get :matches
      end
    end

    post '/messages', to: 'messages#index'
    
    # Make there be a /api/thumbs URL
    # and within that, make POST /api/thumbs/up go to api/thumbs_controller.rb and call "up" method
    # and within that, make POST /api/thumbs/down go to api/thumbs_controller.rb and call "down" method
    # resources :thumbs, only: [] do
    #   collection do
    #     post :up
    #     post :down
    #   end
    # end
    post '/thumbs/up', to: 'thumbs#up'
    post '/thumbs/down', to: 'thumbs#down'

    resources :questions, only: [:index, :show]
  end

  get 'admin222033712', to: 'admin#index'
  
  scope :admin222033712 do
    resources :thumbs
    resources :answers
    resources :users
    resources :questions
  end

  get "*path", to: "application#fallback_index_html"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates :user, presence: true
  validates :question, presence: true
  validates :answer, presence: true

  delegate :kind, to: :question, prefix: true

  # delegate is the same as below
  delegate :name, to: :question, prefix: true
  # def question_name
  #   question.name
  # end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:user_id, :question_id, :answer)
    end
end

app/controllers/api/answers_controller.rb
class Api::AnswersController < ApplicationController
  before_action :authenticate!, only: [:create]

  def index
    @answers = Answer.all
    render json: @answers.map { |a|
      {
        id: a.user.id,
          info:{
            name: a.user.name,
            city: a.user.city,
            question: a.question.name,
            answer: a.answer,
            auth: a.user.auth_id
          }
      }
    }
  end

  def match
    # for later production, so users don't see the same profile twice
    # own_thumbs = current_user.thumbs_made.pluck(:thumbee_id) << current_user.id
    @user = User.where.not(id: params[:currentUser]).order("RANDOM()").first
  end

  def show
    @answers = Answer.find(params[:id])
    render json:  {
      id: @answers.id,
      answer: @answers.answer,
      user: {
        id: @answers.user.id,
        name: @answers.user.name,
      },
      question: {
        id: @answers.question.id,
        question: @answers.question.name
      }
    }
  end

  def create
    answer = Answer.find_or_initialize_by(question_id: params[:q], user_id: current_user.id)

    answer.update(answer: params[:a], user: current_user)

    render json: answer
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.order(name: :ASC), :id, :name, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.collection_select :question_id, Question.order(name: :ASC), :id, :name, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.user_id %></td>
        <td><%= answer.question.name %></td>
        <td><%= answer.answer %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Question:</strong>
  <%= @answer.question.name %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @answer.answer %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>