config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do
    resources :answers, only: [:index, :show, :create] do
      collection do
        get :match
      end
    end
    
    resources :users, only: [:index, :show] do
      collection do
        get :profile
        get :matches
      end
    end

    post '/messages', to: 'messages#index'
    
    # Make there be a /api/thumbs URL
    # and within that, make POST /api/thumbs/up go to api/thumbs_controller.rb and call "up" method
    # and within that, make POST /api/thumbs/down go to api/thumbs_controller.rb and call "down" method
    # resources :thumbs, only: [] do
    #   collection do
    #     post :up
    #     post :down
    #   end
    # end
    post '/thumbs/up', to: 'thumbs#up'
    post '/thumbs/down', to: 'thumbs#down'

    resources :questions, only: [:index, :show]
  end

  get 'admin222033712', to: 'admin#index'
  
  scope :admin222033712 do
    resources :thumbs
    resources :answers
    resources :users
    resources :questions
  end

  get "*path", to: "application#fallback_index_html"
end

app/models/thumb.rb
class Thumb < ApplicationRecord
  belongs_to :thumbee, class_name: "User"
  belongs_to :thumber, class_name: "User"
end

app/controllers/api/thumbs_controller.rb
class Api::ThumbsController < ApplicationController
  def up
    @thumb = Thumb.find_or_initialize_by(thumb_params)
    @thumb.is_up = true
    @thumb.save!
    render json: @thumb
  end

  def down
    @thumb = Thumb.find_or_initialize_by(thumb_params)
    @thumb.is_up = false
    @thumb.save!
    render json: "down"
  end

  private

  def thumb_params
    params.require("thumb").permit(:thumber_id, :thumbee_id)
  end
end

# rails logger debugger
# Rails.logger.debug "Woot!"

app/controllers/thumbs_controller.rb
class ThumbsController < ApplicationController
  before_action :set_thumb, only: [:show, :edit, :update, :destroy]

  # GET /thumbs
  # GET /thumbs.json
  def index
    @thumbs = Thumb.all
  end

  # GET /thumbs/1
  # GET /thumbs/1.json
  def show
  end

  # GET /thumbs/new
  def new
    @thumb = Thumb.new
  end

  # GET /thumbs/1/edit
  def edit
  end

  # POST /thumbs
  # POST /thumbs.json
  def create
    @thumb = Thumb.new(thumb_params)

    respond_to do |format|
      if @thumb.save
        format.html { redirect_to @thumb, notice: 'Thumb was successfully created.' }
        format.json { render :show, status: :created, location: @thumb }
      else
        format.html { render :new }
        format.json { render json: @thumb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thumbs/1
  # PATCH/PUT /thumbs/1.json
  def update
    respond_to do |format|
      if @thumb.update(thumb_params)
        format.html { redirect_to @thumb, notice: 'Thumb was successfully updated.' }
        format.json { render :show, status: :ok, location: @thumb }
      else
        format.html { render :edit }
        format.json { render json: @thumb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thumbs/1
  # DELETE /thumbs/1.json
  def destroy
    @thumb.destroy
    respond_to do |format|
      format.html { redirect_to thumbs_url, notice: 'Thumb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thumb
      @thumb = Thumb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thumb_params
      params.require(:thumb).permit(:user_id, :user_id)
    end
end

app/helpers/thumbs_helper.rb
module ThumbsHelper
end

app/views/thumbs/_form.html.erb
<%= form_with(model: thumb, local: true) do |form| %>
  <% if thumb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thumb.errors.count, "error") %> prohibited this thumb from being saved:</h2>

      <ul>
      <% thumb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/thumbs/edit.html.erb
<h1>Editing Thumb</h1>

<%= render 'form', thumb: @thumb %>

<%= link_to 'Show', @thumb %> |
<%= link_to 'Back', thumbs_path %>

app/views/thumbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Thumbs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thumbs.each do |thumb| %>
      <tr>
        <td><%= thumber.user.name %></td>
        <td><%= thumb.user.name %></td>
        <td><%= link_to 'Show', thumb %></td>
        <td><%= link_to 'Edit', edit_thumb_path(thumb) %></td>
        <td><%= link_to 'Destroy', thumb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thumb', new_thumb_path %>

app/views/thumbs/new.html.erb
<h1>New Thumb</h1>

<%= render 'form', thumb: @thumb %>

<%= link_to 'Back', thumbs_path %>

app/views/thumbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @thumb.user %>
</p>

<p>
  <strong>User:</strong>
  <%= @thumb.user %>
</p>

<%= link_to 'Edit', edit_thumb_path(@thumb) %> |
<%= link_to 'Back', thumbs_path %>